---

apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    tier: some-app
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: some-app
    role: slave

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: some-app
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: some-app
    spec:
      containers:
      - name: slave
        image: redis:latest
        command:
          - redis-server
          - --daemonize
          - "yes"
          - --slaveof
          - redis-master
          - "6379"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---